/** What the innkeepers hear, floor by floor. */
export const RUMOURS: Record<number, string[]> = {
  1: [
  "They say a shrine hides where Whisperwood meets the rim, north-west. Only one gap in the trees leads there.",
  "Foxes nest in a hollow south-east of the fields, behind a wall of trees. Where there's a fox, there's a hoard.",
  "A scholar swore the ruins held a library. The east wall's got a crack you could squeeze through.",
  "Miners won't go past the crystals in the deep caves. Something pale moves down there.",
  "When the Keeper raises his blade high, it's a trick — don't parry too early. Wait for the light.",
  "Waystones remember you once you've touched them. Saves a lot of walking.",
  ],
  2: [
  "The Sentinels in the Sunken Gardens only wake when you step inside their walls. Mostly.",
  "Somebody saw golden feathers blowing off the gardens' north-west edge. There's an island out there, behind the trees.",
  "The Storm Colossus wears a seal on its chest. They say it opens the Stormspire.",
  "Windcallers love the Causeway bridges. One gust and you're flat on your back — keep your feet.",
  "The Aegis knights parry nothing, but their shields turn blows. Get around them.",
  "Brannoc can work gilded plate like soft copper. Bring him some.",
  ],
  3: [
  "Drakes breathe in a cone, not a line. Step to the side, not back — back is where the fire goes.",
  "Something's buried past the canyon's northern ribs. There's a bridge of bone behind the basalt, if you look.",
  "Cindermaw sleeps in the Wyrmrest Caldera. It wears a sigil in its crest — the Roost's doors answer to it.",
  "The obsidian golems are slow, but when they glow, get out of the way. That's not a warning, it's a promise.",
  "Kaela at the Dragonforge works dragonscale like leather. Bring her scales and cinderstone.",
  "They say Ignivar has never lost a fight. They also say nobody has ever reached him. Both can't stay true forever.",
  "The Archivist in the Keep sells scrolls you won't find anywhere else. Bring Marks. Lots of Marks.",
  ],
  4: [
    "Rime wolves hunt in threes and circle before they bite. Keep your back to a rock and your blade out.",
    "The Seer says something sleeps under the Frozen Lake. The Seer says a lot of things. This one, I believe.",
    "There's an old ice bridge west of the lake, behind the rocks on the north shore. Hunters used it, once.",
    "Glacierfang breathes cold, not fire — it'll slow you, and slow is dead. Step out of it, not through it.",
    "In the Glacier Throne, the echoes tell you the runes. Every stone says one. Read them all before you touch anything.",
    "Halla at the Runeforge can carve the cold into steel. Bring her rime shards and pelts.",
    "The Winter King says every fire goes out. He's been saying it for three hundred years. Someone should make him stop.",
  ],
  5: [
    "Shades flicker out of reach and back again. Wait for them to come to you — then don't let them leave.",
    "A cursed thing hits softer and bleeds easier. The Archivist in the Chapel can teach you how to do it to them.",
    "There's a way past the willows at the north end of the Weeping Marsh. The Moonwell is still there, if you believe the old songs.",
    "Nightwing breathes the dark itself. If you stand in it, you won't see the tail coming.",
    "In the Hall of Moons, every lantern drags its neighbour round. Start from the west and work your way east.",
    "Mira at the Moonforge says a void heart weighs nothing and pulls at everything. She keeps hers in a lead box.",
    "When the Queen puts the sun out, find the moonlight. It's the only thing in the Sanctum she can't touch.",
  ],
  6: [
    "A soaked thing is slow, and lightning loves it. Frost sticks to it twice as long. Wet them first, then strike.",
    "Brinehounds come in with the tide. When the Spring Tide's up, stay off the Tidepools, or bring friends.",
    "There's an old pier behind the rocks on the east side of the Tidepools. Nobody goes out there. Nobody comes back.",
    "Scylla nests on the Stormbreak Cliffs. She swallowed the Cathedral's key a hundred years ago and never coughed it up.",
    "In the Cathedral the sea comes in when the bell tolls. Three valves hold it back — and the lowest one drowns first.",
    "Marisol at the Pearlforge says a leviathan scale turns a blade like nothing else. She won't say how she knows.",
    "When the Leviathan Queen calls the Deluge, get to the high ground. It's the only place the sea won't reach.",
  ],
};
